### ISSUE TITLE
Issue when tstep_out > tstop

### ISSUE THREAD

**Issue by hannorein** [carlislewishard/swiftest#15]
When I run
```
sim_gr = swiftest.Simulation(simdir="gr")
sim_gr.add_solar_system_body(["Sun","Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune"])
run_args = {"tstop":10000.0, "dt":0.005, "tstep_out":100000.0, "dump_cadence": 0,"integrator":"whm"}
sim_gr.run(**run_args,general_relativity=True)
```
I get the following error:
```
Traceback (most recent call last):
  File "/gpfs/fs0/scratch/r/rein/rein/swiftest/swiftest/examples/whm_gr_test/whm_gr_test.py", line 59, in <module>
    sim_gr.run(**run_args,general_relativity=True)
  File "/gpfs/fs0/scratch/r/rein/rein/swiftest/swiftest/python/swiftest/swiftest/simulation_class.py", line 517, in run
    self._run_swiftest_driver()
  File "/gpfs/fs0/scratch/r/rein/rein/swiftest/swiftest/python/swiftest/swiftest/simulation_class.py", line 424, in _run_swiftest_driver
    pre_message = f"Time: {self.param['TSTART']:.{twidth}e} / {self.param['TSTOP']:.{twidth}e} {self.TU_name} "
ValueError: Format specifier missing precision
```
The error does not occur when tstep_out <= tstop.

**Comment by profminton** [comment]
I added a sanity check to the `set_simulation_time` method to check whether tstep_out is always <= tstop. If it isn't, a warning is issued and tstep_out is set to be equal to tstop.
